/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package slider_notifi;

/**
 *
 * @author MenDark
 */
public class Ejemplo extends javax.swing.JFrame {

    /**
     * Creates new form Ejemplo
     */
    public Ejemplo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jsliderCustom1 = new slider_notifi.JsliderCustom();
        jsliderCustom2 = new slider_notifi.JsliderCustom();
        jsliderCustom3 = new slider_notifi.JsliderCustom();
        jsliderCustom4 = new slider_notifi.JsliderCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jsliderCustom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jsliderCustom2.setBackground(new java.awt.Color(255, 204, 0));
        jsliderCustom2.setForeground(new java.awt.Color(255, 102, 0));
        jPanel1.add(jsliderCustom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jsliderCustom3.setBackground(new java.awt.Color(153, 204, 0));
        jsliderCustom3.setForeground(new java.awt.Color(255, 153, 255));
        jPanel1.add(jsliderCustom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jsliderCustom4.setBackground(new java.awt.Color(0, 204, 153));
        jsliderCustom4.setForeground(new java.awt.Color(0, 204, 204));
        jPanel1.add(jsliderCustom4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejemplo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private slider_notifi.JsliderCustom jsliderCustom1;
    private slider_notifi.JsliderCustom jsliderCustom2;
    private slider_notifi.JsliderCustom jsliderCustom3;
    private slider_notifi.JsliderCustom jsliderCustom4;
    // End of variables declaration//GEN-END:variables
}
